openapi: 3.0.0
info:
  title: Tshirt store api
  description: A course to create api for ecomm store
  version: 1.0.0
  contact:
    email: sahilbhosale63@live.com
    url: "https://liongueststudios.com"

servers:
  - url: "{protocol}://localhost:4000/api/{version}"
    description: This is a base URL - secure
    variables:
      version:
        enum:
          - v1
          - v2
        default: v1
      protocol:
        enum:
          - http
          - https
        default: http

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: token
    BearerAuth:
      type: http
      scheme: bearer

paths:
  /home:
    get:
      tags:
        - Home
      summary: returns a greeting message
      responses:
        200:
          description: All good success
          content: 
            application/json:
              schema:
                type: string
                example: "mystring"
        400:
          description: bad request
        500:
          description: internal server error